import { DM_Serif_Display, IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

const serif = DM_Serif_Display({
  weight: "400",
  style: "italic",
  subsets: ["latin"],
  variable: "--font-serif",
  display: "swap",
});

const sans = IBM_Plex_Sans({
  weight: ["400", "500"],
  subsets: ["latin"],
  variable: "--font-plex-sans",
  display: "swap",
});

const mono = IBM_Plex_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-plex-mono",
  display: "swap",
});

export const metadata = {
  title: "Leverage AI Partner — The AI Tools Assessment for Small Business",
  description:
    "You don't need more AI. You need the right 3 tools. A 45-minute assessment finds the 3–7 tools that reclaim 5+ hours of your week — guaranteed, or it's free.",
  metadataBase: new URL("https://www.leverageaipartner.com"),
  keywords: [
    "AI tools assessment",
    "AI consulting",
    "AI assessment for small business",
    "AI automation",
    "small business AI",
    "AI tool rationalization",
    "AI implementation",
    "business automation",
    "Phoenix AI consultant",
    "Houston AI consultant",
  ],
  // Icons are auto-generated by app/icon.js and app/apple-icon.js
  openGraph: {
    title: "Leverage AI Partner — The AI Tools Assessment",
    description:
      "A 45-minute assessment finds the 3–7 tools that reclaim 5+ hours of your week — guaranteed, or it's free.",
    type: "website",
    url: "https://www.leverageaipartner.com",
  },
  twitter: {
    card: "summary_large_image",
    title: "Leverage AI Partner",
    description:
      "The AI Tools Assessment for small business. Find 5+ hours a week — guaranteed. Phoenix, AZ & Houston, TX.",
  },
  alternates: {
    canonical: "https://www.leverageaipartner.com",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  name: "Leverage AI Partner",
  description:
    "The AI Tools Assessment for owner-operated small businesses: a 45-minute interview and a 48-hour report prescribing the 3–7 tools that reclaim 5+ hours per week.",
  url: "https://www.leverageaipartner.com",
  email: "hello@leverageaipartner.com",
  areaServed: ["Phoenix, AZ", "Houston, TX", "United States"],
  serviceType: [
    "AI Tools Assessment",
    "AI Implementation",
    "AI Automation",
    "AI Concierge Retainer",
  ],
  employee: [
    {
      "@type": "Person",
      name: "Jermaine Williams",
      jobTitle: "AI Engineer & Consultant",
      address: { "@type": "PostalAddress", addressLocality: "Phoenix", addressRegion: "AZ" },
    },
    {
      "@type": "Person",
      name: "Brandon Davis",
      jobTitle: "AI Engineer & Consultant",
      address: { "@type": "PostalAddress", addressLocality: "Houston", addressRegion: "TX" },
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${serif.variable} ${sans.variable} ${mono.variable}`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
